---
# tasks file for audit

- name: Execute role tasks
  block:

    - name: Include assert.yml
      ansible.builtin.include_tasks: assert.yml
    
    - name: Include audit.yml
      ansible.builtin.include_tasks: audit.yml

  become: yes
